//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITB.VENDIX.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boveda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Boveda()
        {
            this.BovedaMovTemp = new HashSet<BovedaMovTemp>();
            this.BovedaMovTemp1 = new HashSet<BovedaMovTemp>();
            this.BovedaMov = new HashSet<BovedaMov>();
            this.BovedaCuenta = new HashSet<BovedaCuenta>();
        }
    
        public int BovedaId { get; set; }
        public int OficinaId { get; set; }
        public decimal SaldoInicial { get; set; }
        public decimal Entradas { get; set; }
        public decimal Salidas { get; set; }
        public decimal SaldoFinal { get; set; }
        public System.DateTime FechaIniOperacion { get; set; }
        public Nullable<System.DateTime> FechaFinOperacion { get; set; }
        public bool IndCierre { get; set; }
        public bool IndTemporal { get; set; }
    
        public virtual Oficina Oficina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BovedaMovTemp> BovedaMovTemp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BovedaMovTemp> BovedaMovTemp1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BovedaMov> BovedaMov { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BovedaCuenta> BovedaCuenta { get; set; }
    }
}
