//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITB.VENDIX.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CajaChicaDiario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CajaChicaDiario()
        {
            this.MovimientoCajaChica = new HashSet<MovimientoCajaChica>();
        }
    
        public int Id { get; set; }
        public int UsuarioId { get; set; }
        public decimal SaldoInicial { get; set; }
        public decimal Entradas { get; set; }
        public decimal Salidas { get; set; }
        public decimal SaldoFinal { get; set; }
        public System.DateTime FechaIniOperacion { get; set; }
        public Nullable<System.DateTime> FechaFinOperacion { get; set; }
        public bool IndCierre { get; set; }
        public bool TransBoveda { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoCajaChica> MovimientoCajaChica { get; set; }
    }
}
