//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITB.VENDIX.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CierreGerencial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CierreGerencial()
        {
            this.CierreGerencialDetalle = new HashSet<CierreGerencialDetalle>();
            this.VencidoGerencialAperturaDetalle = new HashSet<VencidoGerencialAperturaDetalle>();
        }
    
        public long CierreGerencialId { get; set; }
        public System.DateTime Periodo { get; set; }
        public System.DateTime FechaCorte { get; set; }
        public string Estado { get; set; }
        public int Version { get; set; }
        public int UsuarioCierreId { get; set; }
        public System.DateTime FechaCierre { get; set; }
        public string Observacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CierreGerencialDetalle> CierreGerencialDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VencidoGerencialAperturaDetalle> VencidoGerencialAperturaDetalle { get; set; }
    }
}
