//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITB.VENDIX.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CierreGerencialDetalle
    {
        public long CierreGerencialDetalleId { get; set; }
        public long CierreGerencialId { get; set; }
        public int UsuarioId { get; set; }
        public string NombreUsuario { get; set; }
        public string NombreCompleto { get; set; }
        public string Asesor { get; set; }
        public string Supervisor { get; set; }
        public string Mercado { get; set; }
        public Nullable<short> Orden { get; set; }
        public string TipoCartera { get; set; }
        public string FuenteInicial { get; set; }
        public decimal CapitalCierre { get; set; }
        public int TotalClientesActivos { get; set; }
        public decimal MoraGeneral { get; set; }
        public Nullable<decimal> VencidosCuotasCierre { get; set; }
        public Nullable<int> ClientesVencidosCierre { get; set; }
        public string DefinicionVencidos { get; set; }
        public Nullable<int> ClientesNuevosMes { get; set; }
        public Nullable<decimal> MontoClientesNuevosMes { get; set; }
        public Nullable<decimal> MontoCobradoMes { get; set; }
        public Nullable<decimal> DesembolsosMes { get; set; }
        public Nullable<int> NroOperacionesMes { get; set; }
    
        public virtual CierreGerencial CierreGerencial { get; set; }
    }
}
