//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITB.VENDIX.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditoMora
    {
        public int CreditoMoraId { get; set; }
        public int CreditoId { get; set; }
        public int MovimientoCajaId { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Mora { get; set; }
        public int DiasAtrazo { get; set; }
        public decimal SaldoMora { get; set; }
        public decimal InteresMora { get; set; }
    
        public virtual Credito Credito { get; set; }
        public virtual MovimientoCaja MovimientoCaja { get; set; }
    }
}
