//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITB.VENDIX.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditoCondonacion
    {
        public int Id { get; set; }
        public int CreditoId { get; set; }
        public int CajaDiarioId { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal MoraCondonacion { get; set; }
        public decimal TotalPago { get; set; }
        public bool IndAprobado { get; set; }
    
        public virtual CajaDiario CajaDiario { get; set; }
        public virtual Credito Credito { get; set; }
    }
}
