//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITB.VENDIX.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastosAdm
    {
        public int GastosAdmId { get; set; }
        public string Denominacion { get; set; }
        public decimal MontoMinimo { get; set; }
        public decimal MontoMaximo { get; set; }
        public bool IndPorcentaje { get; set; }
        public decimal Valor { get; set; }
        public bool Estado { get; set; }
        public bool Ind { get; set; }
    }
}
