//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITB.VENDIX.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoCajaChica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovimientoCajaChica()
        {
            this.MovimientoRendidoCajaChica = new HashSet<MovimientoRendidoCajaChica>();
        }
    
        public int Id { get; set; }
        public int CajaChicaDiarioId { get; set; }
        public int PersonaId { get; set; }
        public string Operacion { get; set; }
        public decimal Importe { get; set; }
        public string Descripcion { get; set; }
        public bool IndEntrada { get; set; }
        public bool Estado { get; set; }
        public int UsuarioRegId { get; set; }
        public System.DateTime FechaReg { get; set; }
        public bool IndRendido { get; set; }
        public decimal ImporteRendido { get; set; }
    
        public virtual CajaChicaDiario CajaChicaDiario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoRendidoCajaChica> MovimientoRendidoCajaChica { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
