//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITB.VENDIX.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoCajaExtension
    {
        public int MovimientoCajaId { get; set; }
        public string FechaTransferencia { get; set; }
        public bool IndTransferenciaVerificada { get; set; }
    
        public virtual MovimientoCaja MovimientoCaja { get; set; }
    }
}
