//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITB.VENDIX.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaldoCarteraMensual
    {
        public int SaldoCarteraId { get; set; }
        public int OficinaId { get; set; }
        public int AgenteId { get; set; }
        public int Anio { get; set; }
        public int Mes { get; set; }
        public System.DateTime FechaCierre { get; set; }
        public int NroDesembolsos { get; set; }
        public decimal MontoDesembolsos { get; set; }
        public decimal SaldoCartera { get; set; }
        public int NroClientesSaldoCartera { get; set; }
        public decimal SaldoMoraCartera { get; set; }
        public int NroClientesSaldoMoraCartera { get; set; }
        public decimal SaldoVencido { get; set; }
        public decimal SaldoMorosidad { get; set; }
        public int NroClientesNuevos { get; set; }
    }
}
