//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITB.VENDIX.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SerieArticulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SerieArticulo()
        {
            this.OrdenVentaDetSerie = new HashSet<OrdenVentaDetSerie>();
            this.TransferenciaSerie = new HashSet<TransferenciaSerie>();
        }
    
        public int SerieArticuloId { get; set; }
        public string NumeroSerie { get; set; }
        public int AlmacenId { get; set; }
        public int ArticuloId { get; set; }
        public int EstadoId { get; set; }
        public Nullable<int> MovimientoDetEntId { get; set; }
        public Nullable<int> MovimientoDetSalId { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual Articulo Articulo { get; set; }
        public virtual MovimientoDet MovimientoDet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenVentaDetSerie> OrdenVentaDetSerie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferenciaSerie> TransferenciaSerie { get; set; }
    }
}
