//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITB.VENDIX.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoDocumento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoDocumento()
        {
            this.MovimientoDoc = new HashSet<MovimientoDoc>();
            this.MovimientoRendidoCajaChica = new HashSet<MovimientoRendidoCajaChica>();
        }
    
        public int TipoDocumentoId { get; set; }
        public string Denominacion { get; set; }
        public string Descripcion { get; set; }
        public bool IndVenta { get; set; }
        public bool IndAlmacen { get; set; }
        public bool IndAlmacenMov { get; set; }
        public bool IndCajaChica { get; set; }
        public bool Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoDoc> MovimientoDoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoRendidoCajaChica> MovimientoRendidoCajaChica { get; set; }
    }
}
