//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITB.VENDIX.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoArticulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoArticulo()
        {
            this.Articulo = new HashSet<Articulo>();
        }
    
        public int TipoArticuloId { get; set; }
        public string Denominacion { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> IndTieneCodigo { get; set; }
        public bool Estado { get; set; }
        public Nullable<bool> IndMovimientoAlmacen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Articulo> Articulo { get; set; }
    }
}
