//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITB.VENDIX.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class VencidoGerencialAperturaDetalle
    {
        public long VencidoGerencialAperturaDetalleId { get; set; }
        public System.DateTime Periodo { get; set; }
        public int UsuarioId { get; set; }
        public int CreditoId { get; set; }
        public int PlanPagoId { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public decimal SaldoVencidoApertura { get; set; }
        public long CierreOrigenId { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual CierreGerencial CierreGerencial { get; set; }
    }
}
