//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITB.VENDIX.DA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VENDIXEntities : DbContext
    {
        public VENDIXEntities()
            : base("name=VENDIXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Almacen> Almacen { get; set; }
        public virtual DbSet<Articulo> Articulo { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<Modelo> Modelo { get; set; }
        public virtual DbSet<Movimiento> Movimiento { get; set; }
        public virtual DbSet<MovimientoDet> MovimientoDet { get; set; }
        public virtual DbSet<MovimientoDoc> MovimientoDoc { get; set; }
        public virtual DbSet<SerieArticulo> SerieArticulo { get; set; }
        public virtual DbSet<TipoArticulo> TipoArticulo { get; set; }
        public virtual DbSet<TipoMovimiento> TipoMovimiento { get; set; }
        public virtual DbSet<Transferencia> Transferencia { get; set; }
        public virtual DbSet<TransferenciaSerie> TransferenciaSerie { get; set; }
        public virtual DbSet<Aprobacion> Aprobacion { get; set; }
        public virtual DbSet<Boveda> Boveda { get; set; }
        public virtual DbSet<BovedaMovTemp> BovedaMovTemp { get; set; }
        public virtual DbSet<Caja> Caja { get; set; }
        public virtual DbSet<CajaChicaDiario> CajaChicaDiario { get; set; }
        public virtual DbSet<CajaDiario> CajaDiario { get; set; }
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<CentralRiesgo> CentralRiesgo { get; set; }
        public virtual DbSet<Credito> Credito { get; set; }
        public virtual DbSet<CreditoImagen> CreditoImagen { get; set; }
        public virtual DbSet<CuentaxCobrar> CuentaxCobrar { get; set; }
        public virtual DbSet<GastosAdm> GastosAdm { get; set; }
        public virtual DbSet<MovimientoCaja> MovimientoCaja { get; set; }
        public virtual DbSet<MovimientoCajaAnu> MovimientoCajaAnu { get; set; }
        public virtual DbSet<MovimientoCajaChica> MovimientoCajaChica { get; set; }
        public virtual DbSet<MovimientoCajaExtension> MovimientoCajaExtension { get; set; }
        public virtual DbSet<MovimientoRendidoCajaChica> MovimientoRendidoCajaChica { get; set; }
        public virtual DbSet<PlanPago> PlanPago { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<SaldoCarteraMensual> SaldoCarteraMensual { get; set; }
        public virtual DbSet<Acceso> Acceso { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Distrito> Distrito { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Oficina> Oficina { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<PersonaDepurado> PersonaDepurado { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<RolMenu> RolMenu { get; set; }
        public virtual DbSet<TipoDocumento> TipoDocumento { get; set; }
        public virtual DbSet<TipoOperacion> TipoOperacion { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioOficina> UsuarioOficina { get; set; }
        public virtual DbSet<UsuarioRol> UsuarioRol { get; set; }
        public virtual DbSet<ValorTabla> ValorTabla { get; set; }
        public virtual DbSet<ListaPrecio> ListaPrecio { get; set; }
        public virtual DbSet<OrdenVenta> OrdenVenta { get; set; }
        public virtual DbSet<OrdenVentaDet> OrdenVentaDet { get; set; }
        public virtual DbSet<OrdenVentaDetSerie> OrdenVentaDetSerie { get; set; }
        public virtual DbSet<TarjetaPunto> TarjetaPunto { get; set; }
        public virtual DbSet<TarjetaPuntoDet> TarjetaPuntoDet { get; set; }
        public virtual DbSet<BovedaMov> BovedaMov { get; set; }
        public virtual DbSet<BovedaCuenta> BovedaCuenta { get; set; }
        public virtual DbSet<Ocupacion> Ocupacion { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Subtarea> Subtarea { get; set; }
        public virtual DbSet<Tarea> Tarea { get; set; }
        public virtual DbSet<CreditoMora> CreditoMora { get; set; }
    
        [DbFunction("VENDIXEntities", "Split")]
        public virtual IQueryable<Split_Result> Split(string stringToSplit, string separador)
        {
            var stringToSplitParameter = stringToSplit != null ?
                new ObjectParameter("stringToSplit", stringToSplit) :
                new ObjectParameter("stringToSplit", typeof(string));
    
            var separadorParameter = separador != null ?
                new ObjectParameter("Separador", separador) :
                new ObjectParameter("Separador", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Split_Result>("[VENDIXEntities].[Split](@stringToSplit, @Separador)", stringToSplitParameter, separadorParameter);
        }
    
        public virtual int usp_CrearMovimientoDet(Nullable<int> movimientoId, Nullable<int> movimientoDetId, Nullable<int> articuloId, Nullable<bool> indAutogenerar, string listaSerie, Nullable<int> cantidad, Nullable<bool> indCorrelativo, Nullable<decimal> precioUnitario, Nullable<decimal> descuento, Nullable<int> medida)
        {
            var movimientoIdParameter = movimientoId.HasValue ?
                new ObjectParameter("MovimientoId", movimientoId) :
                new ObjectParameter("MovimientoId", typeof(int));
    
            var movimientoDetIdParameter = movimientoDetId.HasValue ?
                new ObjectParameter("MovimientoDetId", movimientoDetId) :
                new ObjectParameter("MovimientoDetId", typeof(int));
    
            var articuloIdParameter = articuloId.HasValue ?
                new ObjectParameter("ArticuloId", articuloId) :
                new ObjectParameter("ArticuloId", typeof(int));
    
            var indAutogenerarParameter = indAutogenerar.HasValue ?
                new ObjectParameter("IndAutogenerar", indAutogenerar) :
                new ObjectParameter("IndAutogenerar", typeof(bool));
    
            var listaSerieParameter = listaSerie != null ?
                new ObjectParameter("ListaSerie", listaSerie) :
                new ObjectParameter("ListaSerie", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(int));
    
            var indCorrelativoParameter = indCorrelativo.HasValue ?
                new ObjectParameter("IndCorrelativo", indCorrelativo) :
                new ObjectParameter("IndCorrelativo", typeof(bool));
    
            var precioUnitarioParameter = precioUnitario.HasValue ?
                new ObjectParameter("PrecioUnitario", precioUnitario) :
                new ObjectParameter("PrecioUnitario", typeof(decimal));
    
            var descuentoParameter = descuento.HasValue ?
                new ObjectParameter("Descuento", descuento) :
                new ObjectParameter("Descuento", typeof(decimal));
    
            var medidaParameter = medida.HasValue ?
                new ObjectParameter("Medida", medida) :
                new ObjectParameter("Medida", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CrearMovimientoDet", movimientoIdParameter, movimientoDetIdParameter, articuloIdParameter, indAutogenerarParameter, listaSerieParameter, cantidadParameter, indCorrelativoParameter, precioUnitarioParameter, descuentoParameter, medidaParameter);
        }
    
        public virtual int usp_EliminarMovimientoDet(Nullable<int> movimientoDetId)
        {
            var movimientoDetIdParameter = movimientoDetId.HasValue ?
                new ObjectParameter("MovimientoDetId", movimientoDetId) :
                new ObjectParameter("MovimientoDetId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarMovimientoDet", movimientoDetIdParameter);
        }
    
        public virtual ObjectResult<string> usp_ExisteSerieArticulo(string listaSerie, Nullable<int> cantidad, Nullable<bool> indCorrelativo)
        {
            var listaSerieParameter = listaSerie != null ?
                new ObjectParameter("ListaSerie", listaSerie) :
                new ObjectParameter("ListaSerie", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(int));
    
            var indCorrelativoParameter = indCorrelativo.HasValue ?
                new ObjectParameter("IndCorrelativo", indCorrelativo) :
                new ObjectParameter("IndCorrelativo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_ExisteSerieArticulo", listaSerieParameter, cantidadParameter, indCorrelativoParameter);
        }
    
        public virtual ObjectResult<usp_GenerarKardex_Result> usp_GenerarKardex(Nullable<int> articuloId, Nullable<int> almacenId)
        {
            var articuloIdParameter = articuloId.HasValue ?
                new ObjectParameter("ArticuloId", articuloId) :
                new ObjectParameter("ArticuloId", typeof(int));
    
            var almacenIdParameter = almacenId.HasValue ?
                new ObjectParameter("AlmacenId", almacenId) :
                new ObjectParameter("AlmacenId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GenerarKardex_Result>("usp_GenerarKardex", articuloIdParameter, almacenIdParameter);
        }
    
        public virtual ObjectResult<string> usp_ListarSerieKardex(Nullable<int> movimientoDetalleId, Nullable<bool> indStock)
        {
            var movimientoDetalleIdParameter = movimientoDetalleId.HasValue ?
                new ObjectParameter("MovimientoDetalleId", movimientoDetalleId) :
                new ObjectParameter("MovimientoDetalleId", typeof(int));
    
            var indStockParameter = indStock.HasValue ?
                new ObjectParameter("IndStock", indStock) :
                new ObjectParameter("IndStock", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_ListarSerieKardex", movimientoDetalleIdParameter, indStockParameter);
        }
    
        public virtual ObjectResult<string> usp_Movimiento_Upd(Nullable<int> flag, Nullable<int> movimientoId, Nullable<int> tipoMovimientoId, Nullable<System.DateTime> fechaMov, string observacion)
        {
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(int));
    
            var movimientoIdParameter = movimientoId.HasValue ?
                new ObjectParameter("MovimientoId", movimientoId) :
                new ObjectParameter("MovimientoId", typeof(int));
    
            var tipoMovimientoIdParameter = tipoMovimientoId.HasValue ?
                new ObjectParameter("TipoMovimientoId", tipoMovimientoId) :
                new ObjectParameter("TipoMovimientoId", typeof(int));
    
            var fechaMovParameter = fechaMov.HasValue ?
                new ObjectParameter("FechaMov", fechaMov) :
                new ObjectParameter("FechaMov", typeof(System.DateTime));
    
            var observacionParameter = observacion != null ?
                new ObjectParameter("Observacion", observacion) :
                new ObjectParameter("Observacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_Movimiento_Upd", flagParameter, movimientoIdParameter, tipoMovimientoIdParameter, fechaMovParameter, observacionParameter);
        }
    
        public virtual ObjectResult<usp_ReporteStock_Result> usp_ReporteStock(Nullable<int> oficinaId)
        {
            var oficinaIdParameter = oficinaId.HasValue ?
                new ObjectParameter("OficinaId", oficinaId) :
                new ObjectParameter("OficinaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ReporteStock_Result>("usp_ReporteStock", oficinaIdParameter);
        }
    
        public virtual int ActualizarClientesNuevos(Nullable<int> cajaDiarioId)
        {
            var cajaDiarioIdParameter = cajaDiarioId.HasValue ?
                new ObjectParameter("CajaDiarioId", cajaDiarioId) :
                new ObjectParameter("CajaDiarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarClientesNuevos", cajaDiarioIdParameter);
        }
    
        public virtual int usp_ActualizarSaldoCartera(Nullable<int> oficinaId)
        {
            var oficinaIdParameter = oficinaId.HasValue ?
                new ObjectParameter("OficinaId", oficinaId) :
                new ObjectParameter("OficinaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarSaldoCartera", oficinaIdParameter);
        }
    
        public virtual int usp_ActualizarSaldosBoveda(Nullable<int> bovedaId)
        {
            var bovedaIdParameter = bovedaId.HasValue ?
                new ObjectParameter("BovedaId", bovedaId) :
                new ObjectParameter("BovedaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarSaldosBoveda", bovedaIdParameter);
        }
    
        public virtual int usp_ActualizarSaldosCajaDiario(Nullable<int> usuarioId, Nullable<int> oficinaId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var oficinaIdParameter = oficinaId.HasValue ?
                new ObjectParameter("OficinaId", oficinaId) :
                new ObjectParameter("OficinaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarSaldosCajaDiario", usuarioIdParameter, oficinaIdParameter);
        }
    
        public virtual int usp_CalcularMontoPorCobrar(Nullable<int> usuarioId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CalcularMontoPorCobrar", usuarioIdParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> usp_CalcularMoraPendiente(Nullable<int> creditoId)
        {
            var creditoIdParameter = creditoId.HasValue ?
                new ObjectParameter("CreditoId", creditoId) :
                new ObjectParameter("CreditoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("usp_CalcularMoraPendiente", creditoIdParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> usp_CalcularTEM(Nullable<decimal> tEA, string formaPago)
        {
            var tEAParameter = tEA.HasValue ?
                new ObjectParameter("TEA", tEA) :
                new ObjectParameter("TEA", typeof(decimal));
    
            var formaPagoParameter = formaPago != null ?
                new ObjectParameter("FormaPago", formaPago) :
                new ObjectParameter("FormaPago", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("usp_CalcularTEM", tEAParameter, formaPagoParameter);
        }
    
        public virtual int usp_CalificarCliente(Nullable<int> oficinaId)
        {
            var oficinaIdParameter = oficinaId.HasValue ?
                new ObjectParameter("OficinaId", oficinaId) :
                new ObjectParameter("OficinaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CalificarCliente", oficinaIdParameter);
        }
    
        public virtual ObjectResult<usp_CentralRiesgoGenerar_Result> usp_CentralRiesgoGenerar(Nullable<int> oficinaId, Nullable<int> anio, Nullable<int> mes)
        {
            var oficinaIdParameter = oficinaId.HasValue ?
                new ObjectParameter("OficinaId", oficinaId) :
                new ObjectParameter("OficinaId", typeof(int));
    
            var anioParameter = anio.HasValue ?
                new ObjectParameter("Anio", anio) :
                new ObjectParameter("Anio", typeof(int));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("Mes", mes) :
                new ObjectParameter("Mes", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CentralRiesgoGenerar_Result>("usp_CentralRiesgoGenerar", oficinaIdParameter, anioParameter, mesParameter);
        }
    
        public virtual int usp_CerrarBovedaTemporal(Nullable<int> oficinaId, Nullable<int> usuarioRegId)
        {
            var oficinaIdParameter = oficinaId.HasValue ?
                new ObjectParameter("OficinaId", oficinaId) :
                new ObjectParameter("OficinaId", typeof(int));
    
            var usuarioRegIdParameter = usuarioRegId.HasValue ?
                new ObjectParameter("UsuarioRegId", usuarioRegId) :
                new ObjectParameter("UsuarioRegId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CerrarBovedaTemporal", oficinaIdParameter, usuarioRegIdParameter);
        }
    
        public virtual int usp_CompletarImpagos(Nullable<int> cajaDiarioId)
        {
            var cajaDiarioIdParameter = cajaDiarioId.HasValue ?
                new ObjectParameter("CajaDiarioId", cajaDiarioId) :
                new ObjectParameter("CajaDiarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CompletarImpagos", cajaDiarioIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_CompletarImpagosValidacion(Nullable<int> cajaDiarioId)
        {
            var cajaDiarioIdParameter = cajaDiarioId.HasValue ?
                new ObjectParameter("CajaDiarioId", cajaDiarioId) :
                new ObjectParameter("CajaDiarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_CompletarImpagosValidacion", cajaDiarioIdParameter);
        }
    
        public virtual int usp_Credito_Del(Nullable<int> creditoId, string observacion, Nullable<int> usuarioId)
        {
            var creditoIdParameter = creditoId.HasValue ?
                new ObjectParameter("CreditoId", creditoId) :
                new ObjectParameter("CreditoId", typeof(int));
    
            var observacionParameter = observacion != null ?
                new ObjectParameter("Observacion", observacion) :
                new ObjectParameter("Observacion", typeof(string));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Credito_Del", creditoIdParameter, observacionParameter, usuarioIdParameter);
        }
    
        public virtual ObjectResult<string> usp_Credito_Ins(Nullable<int> solicitudCreditoId, Nullable<int> productoId, string tipoCuota, Nullable<decimal> montoInicial, Nullable<decimal> montoCredito, Nullable<decimal> montoGastosAdm, string indGastoAdm, string formaPago, Nullable<int> nroCuotas, Nullable<decimal> interes, Nullable<System.DateTime> fechaPrimerPago, string observacion, Nullable<int> usuarioId, Nullable<bool> indCentralRiesgo)
        {
            var solicitudCreditoIdParameter = solicitudCreditoId.HasValue ?
                new ObjectParameter("SolicitudCreditoId", solicitudCreditoId) :
                new ObjectParameter("SolicitudCreditoId", typeof(int));
    
            var productoIdParameter = productoId.HasValue ?
                new ObjectParameter("ProductoId", productoId) :
                new ObjectParameter("ProductoId", typeof(int));
    
            var tipoCuotaParameter = tipoCuota != null ?
                new ObjectParameter("TipoCuota", tipoCuota) :
                new ObjectParameter("TipoCuota", typeof(string));
    
            var montoInicialParameter = montoInicial.HasValue ?
                new ObjectParameter("MontoInicial", montoInicial) :
                new ObjectParameter("MontoInicial", typeof(decimal));
    
            var montoCreditoParameter = montoCredito.HasValue ?
                new ObjectParameter("MontoCredito", montoCredito) :
                new ObjectParameter("MontoCredito", typeof(decimal));
    
            var montoGastosAdmParameter = montoGastosAdm.HasValue ?
                new ObjectParameter("MontoGastosAdm", montoGastosAdm) :
                new ObjectParameter("MontoGastosAdm", typeof(decimal));
    
            var indGastoAdmParameter = indGastoAdm != null ?
                new ObjectParameter("IndGastoAdm", indGastoAdm) :
                new ObjectParameter("IndGastoAdm", typeof(string));
    
            var formaPagoParameter = formaPago != null ?
                new ObjectParameter("FormaPago", formaPago) :
                new ObjectParameter("FormaPago", typeof(string));
    
            var nroCuotasParameter = nroCuotas.HasValue ?
                new ObjectParameter("NroCuotas", nroCuotas) :
                new ObjectParameter("NroCuotas", typeof(int));
    
            var interesParameter = interes.HasValue ?
                new ObjectParameter("Interes", interes) :
                new ObjectParameter("Interes", typeof(decimal));
    
            var fechaPrimerPagoParameter = fechaPrimerPago.HasValue ?
                new ObjectParameter("FechaPrimerPago", fechaPrimerPago) :
                new ObjectParameter("FechaPrimerPago", typeof(System.DateTime));
    
            var observacionParameter = observacion != null ?
                new ObjectParameter("Observacion", observacion) :
                new ObjectParameter("Observacion", typeof(string));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var indCentralRiesgoParameter = indCentralRiesgo.HasValue ?
                new ObjectParameter("IndCentralRiesgo", indCentralRiesgo) :
                new ObjectParameter("IndCentralRiesgo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_Credito_Ins", solicitudCreditoIdParameter, productoIdParameter, tipoCuotaParameter, montoInicialParameter, montoCreditoParameter, montoGastosAdmParameter, indGastoAdmParameter, formaPagoParameter, nroCuotasParameter, interesParameter, fechaPrimerPagoParameter, observacionParameter, usuarioIdParameter, indCentralRiesgoParameter);
        }
    
        public virtual int usp_Credito_Upd(Nullable<int> opcion, Nullable<int> creditoId, Nullable<int> usuarioId)
        {
            var opcionParameter = opcion.HasValue ?
                new ObjectParameter("Opcion", opcion) :
                new ObjectParameter("Opcion", typeof(int));
    
            var creditoIdParameter = creditoId.HasValue ?
                new ObjectParameter("CreditoId", creditoId) :
                new ObjectParameter("CreditoId", typeof(int));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Credito_Upd", opcionParameter, creditoIdParameter, usuarioIdParameter);
        }
    
        public virtual ObjectResult<usp_CuotasPendientes_Result> usp_CuotasPendientes(Nullable<int> creditoId, Nullable<System.DateTime> fechaCalculo, Nullable<bool> indCancelacion)
        {
            var creditoIdParameter = creditoId.HasValue ?
                new ObjectParameter("CreditoId", creditoId) :
                new ObjectParameter("CreditoId", typeof(int));
    
            var fechaCalculoParameter = fechaCalculo.HasValue ?
                new ObjectParameter("FechaCalculo", fechaCalculo) :
                new ObjectParameter("FechaCalculo", typeof(System.DateTime));
    
            var indCancelacionParameter = indCancelacion.HasValue ?
                new ObjectParameter("IndCancelacion", indCancelacion) :
                new ObjectParameter("IndCancelacion", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CuotasPendientes_Result>("usp_CuotasPendientes", creditoIdParameter, fechaCalculoParameter, indCancelacionParameter);
        }
    
        public virtual int usp_EntradaSalidaCajaChicaDiario(Nullable<int> cajaChicaDiarioId, Nullable<int> personaId, Nullable<int> tipoOperacionId, Nullable<decimal> importe, string decripcion, Nullable<int> usuarioId)
        {
            var cajaChicaDiarioIdParameter = cajaChicaDiarioId.HasValue ?
                new ObjectParameter("CajaChicaDiarioId", cajaChicaDiarioId) :
                new ObjectParameter("CajaChicaDiarioId", typeof(int));
    
            var personaIdParameter = personaId.HasValue ?
                new ObjectParameter("PersonaId", personaId) :
                new ObjectParameter("PersonaId", typeof(int));
    
            var tipoOperacionIdParameter = tipoOperacionId.HasValue ?
                new ObjectParameter("TipoOperacionId", tipoOperacionId) :
                new ObjectParameter("TipoOperacionId", typeof(int));
    
            var importeParameter = importe.HasValue ?
                new ObjectParameter("Importe", importe) :
                new ObjectParameter("Importe", typeof(decimal));
    
            var decripcionParameter = decripcion != null ?
                new ObjectParameter("Decripcion", decripcion) :
                new ObjectParameter("Decripcion", typeof(string));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EntradaSalidaCajaChicaDiario", cajaChicaDiarioIdParameter, personaIdParameter, tipoOperacionIdParameter, importeParameter, decripcionParameter, usuarioIdParameter);
        }
    
        public virtual int usp_EntradaSalidaCajaDiario(Nullable<int> cajaDiarioId, Nullable<int> personaId, Nullable<int> tipoOperacionId, Nullable<decimal> importe, string decripcion, Nullable<int> usuarioId, Nullable<int> tipoPagoId)
        {
            var cajaDiarioIdParameter = cajaDiarioId.HasValue ?
                new ObjectParameter("CajaDiarioId", cajaDiarioId) :
                new ObjectParameter("CajaDiarioId", typeof(int));
    
            var personaIdParameter = personaId.HasValue ?
                new ObjectParameter("PersonaId", personaId) :
                new ObjectParameter("PersonaId", typeof(int));
    
            var tipoOperacionIdParameter = tipoOperacionId.HasValue ?
                new ObjectParameter("TipoOperacionId", tipoOperacionId) :
                new ObjectParameter("TipoOperacionId", typeof(int));
    
            var importeParameter = importe.HasValue ?
                new ObjectParameter("Importe", importe) :
                new ObjectParameter("Importe", typeof(decimal));
    
            var decripcionParameter = decripcion != null ?
                new ObjectParameter("Decripcion", decripcion) :
                new ObjectParameter("Decripcion", typeof(string));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var tipoPagoIdParameter = tipoPagoId.HasValue ?
                new ObjectParameter("TipoPagoId", tipoPagoId) :
                new ObjectParameter("TipoPagoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EntradaSalidaCajaDiario", cajaDiarioIdParameter, personaIdParameter, tipoOperacionIdParameter, importeParameter, decripcionParameter, usuarioIdParameter, tipoPagoIdParameter);
        }
    
        public virtual ObjectResult<usp_EstadoPlanPago_Result> usp_EstadoPlanPago(Nullable<int> creditoId)
        {
            var creditoIdParameter = creditoId.HasValue ?
                new ObjectParameter("CreditoId", creditoId) :
                new ObjectParameter("CreditoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_EstadoPlanPago_Result>("usp_EstadoPlanPago", creditoIdParameter);
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> usp_FechaBD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("usp_FechaBD");
        }
    
        public virtual ObjectResult<usp_ListarSaldoCartera_Result> usp_ListarSaldoCartera(Nullable<int> anio, Nullable<int> mes, Nullable<int> oficinaId, Nullable<int> usuarioId)
        {
            var anioParameter = anio.HasValue ?
                new ObjectParameter("Anio", anio) :
                new ObjectParameter("Anio", typeof(int));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("Mes", mes) :
                new ObjectParameter("Mes", typeof(int));
    
            var oficinaIdParameter = oficinaId.HasValue ?
                new ObjectParameter("OficinaId", oficinaId) :
                new ObjectParameter("OficinaId", typeof(int));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarSaldoCartera_Result>("usp_ListarSaldoCartera", anioParameter, mesParameter, oficinaIdParameter, usuarioIdParameter);
        }
    
        public virtual int usp_MovimientoCaja_Del(Nullable<int> movimientoCajaId, string observacion, Nullable<int> usuarioId)
        {
            var movimientoCajaIdParameter = movimientoCajaId.HasValue ?
                new ObjectParameter("MovimientoCajaId", movimientoCajaId) :
                new ObjectParameter("MovimientoCajaId", typeof(int));
    
            var observacionParameter = observacion != null ?
                new ObjectParameter("Observacion", observacion) :
                new ObjectParameter("Observacion", typeof(string));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_MovimientoCaja_Del", movimientoCajaIdParameter, observacionParameter, usuarioIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_PagarCuentaxCobrar(Nullable<int> ordenVentaId, Nullable<int> cuentaxCobrarId, Nullable<int> cajaDiarioId, Nullable<int> usuarioId)
        {
            var ordenVentaIdParameter = ordenVentaId.HasValue ?
                new ObjectParameter("OrdenVentaId", ordenVentaId) :
                new ObjectParameter("OrdenVentaId", typeof(int));
    
            var cuentaxCobrarIdParameter = cuentaxCobrarId.HasValue ?
                new ObjectParameter("CuentaxCobrarId", cuentaxCobrarId) :
                new ObjectParameter("CuentaxCobrarId", typeof(int));
    
            var cajaDiarioIdParameter = cajaDiarioId.HasValue ?
                new ObjectParameter("CajaDiarioId", cajaDiarioId) :
                new ObjectParameter("CajaDiarioId", typeof(int));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_PagarCuentaxCobrar", ordenVentaIdParameter, cuentaxCobrarIdParameter, cajaDiarioIdParameter, usuarioIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_PagarCuotaPagoLibre(Nullable<int> cajaDiarioId, Nullable<int> creditoId, Nullable<decimal> importeRecibido, Nullable<int> usuarioId, Nullable<int> tipoPagoId, string fechaPagoTransferencia)
        {
            var cajaDiarioIdParameter = cajaDiarioId.HasValue ?
                new ObjectParameter("CajaDiarioId", cajaDiarioId) :
                new ObjectParameter("CajaDiarioId", typeof(int));
    
            var creditoIdParameter = creditoId.HasValue ?
                new ObjectParameter("CreditoId", creditoId) :
                new ObjectParameter("CreditoId", typeof(int));
    
            var importeRecibidoParameter = importeRecibido.HasValue ?
                new ObjectParameter("ImporteRecibido", importeRecibido) :
                new ObjectParameter("ImporteRecibido", typeof(decimal));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var tipoPagoIdParameter = tipoPagoId.HasValue ?
                new ObjectParameter("TipoPagoId", tipoPagoId) :
                new ObjectParameter("TipoPagoId", typeof(int));
    
            var fechaPagoTransferenciaParameter = fechaPagoTransferencia != null ?
                new ObjectParameter("FechaPagoTransferencia", fechaPagoTransferencia) :
                new ObjectParameter("FechaPagoTransferencia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_PagarCuotaPagoLibre", cajaDiarioIdParameter, creditoIdParameter, importeRecibidoParameter, usuarioIdParameter, tipoPagoIdParameter, fechaPagoTransferenciaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_PagarCuotas(Nullable<int> cajaDiarioId, Nullable<int> creditoId, string listaPlanPagoId, Nullable<decimal> importeRecibido, Nullable<int> usuarioId, Nullable<System.DateTime> fechaPago, Nullable<int> tipoPagoId, string fechaPagoTransferencia)
        {
            var cajaDiarioIdParameter = cajaDiarioId.HasValue ?
                new ObjectParameter("CajaDiarioId", cajaDiarioId) :
                new ObjectParameter("CajaDiarioId", typeof(int));
    
            var creditoIdParameter = creditoId.HasValue ?
                new ObjectParameter("CreditoId", creditoId) :
                new ObjectParameter("CreditoId", typeof(int));
    
            var listaPlanPagoIdParameter = listaPlanPagoId != null ?
                new ObjectParameter("ListaPlanPagoId", listaPlanPagoId) :
                new ObjectParameter("ListaPlanPagoId", typeof(string));
    
            var importeRecibidoParameter = importeRecibido.HasValue ?
                new ObjectParameter("ImporteRecibido", importeRecibido) :
                new ObjectParameter("ImporteRecibido", typeof(decimal));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var fechaPagoParameter = fechaPago.HasValue ?
                new ObjectParameter("FechaPago", fechaPago) :
                new ObjectParameter("FechaPago", typeof(System.DateTime));
    
            var tipoPagoIdParameter = tipoPagoId.HasValue ?
                new ObjectParameter("TipoPagoId", tipoPagoId) :
                new ObjectParameter("TipoPagoId", typeof(int));
    
            var fechaPagoTransferenciaParameter = fechaPagoTransferencia != null ?
                new ObjectParameter("FechaPagoTransferencia", fechaPagoTransferencia) :
                new ObjectParameter("FechaPagoTransferencia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_PagarCuotas", cajaDiarioIdParameter, creditoIdParameter, listaPlanPagoIdParameter, importeRecibidoParameter, usuarioIdParameter, fechaPagoParameter, tipoPagoIdParameter, fechaPagoTransferenciaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_PagarCuotasCancelacion(Nullable<int> cajaDiarioId, Nullable<int> creditoId, Nullable<int> usuarioId, Nullable<System.DateTime> fechaPago)
        {
            var cajaDiarioIdParameter = cajaDiarioId.HasValue ?
                new ObjectParameter("CajaDiarioId", cajaDiarioId) :
                new ObjectParameter("CajaDiarioId", typeof(int));
    
            var creditoIdParameter = creditoId.HasValue ?
                new ObjectParameter("CreditoId", creditoId) :
                new ObjectParameter("CreditoId", typeof(int));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var fechaPagoParameter = fechaPago.HasValue ?
                new ObjectParameter("FechaPago", fechaPago) :
                new ObjectParameter("FechaPago", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_PagarCuotasCancelacion", cajaDiarioIdParameter, creditoIdParameter, usuarioIdParameter, fechaPagoParameter);
        }
    
        public virtual ObjectResult<usp_PagosNoVerificados_Result> usp_PagosNoVerificados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_PagosNoVerificados_Result>("usp_PagosNoVerificados");
        }
    
        public virtual int usp_ProrrogarCredito(Nullable<int> creditoId, Nullable<int> dias)
        {
            var creditoIdParameter = creditoId.HasValue ?
                new ObjectParameter("CreditoId", creditoId) :
                new ObjectParameter("CreditoId", typeof(int));
    
            var diasParameter = dias.HasValue ?
                new ObjectParameter("Dias", dias) :
                new ObjectParameter("Dias", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ProrrogarCredito", creditoIdParameter, diasParameter);
        }
    
        public virtual int usp_RecalcularCajaDiario(Nullable<int> cajaDiarioId)
        {
            var cajaDiarioIdParameter = cajaDiarioId.HasValue ?
                new ObjectParameter("CajaDiarioId", cajaDiarioId) :
                new ObjectParameter("CajaDiarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_RecalcularCajaDiario", cajaDiarioIdParameter);
        }
    
        public virtual int usp_ReconciliarCajaDiario(Nullable<int> cajaDiarioId)
        {
            var cajaDiarioIdParameter = cajaDiarioId.HasValue ?
                new ObjectParameter("CajaDiarioId", cajaDiarioId) :
                new ObjectParameter("CajaDiarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ReconciliarCajaDiario", cajaDiarioIdParameter);
        }
    
        public virtual int usp_RegenerarPlanPago(Nullable<int> creditoId)
        {
            var creditoIdParameter = creditoId.HasValue ?
                new ObjectParameter("CreditoId", creditoId) :
                new ObjectParameter("CreditoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_RegenerarPlanPago", creditoIdParameter);
        }
    
        public virtual int usp_ReprogramarCredito(Nullable<int> creditoId, Nullable<int> usuarioId)
        {
            var creditoIdParameter = creditoId.HasValue ?
                new ObjectParameter("CreditoId", creditoId) :
                new ObjectParameter("CreditoId", typeof(int));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ReprogramarCredito", creditoIdParameter, usuarioIdParameter);
        }
    
        public virtual ObjectResult<usp_RptAval_Result> usp_RptAval(Nullable<int> personaId)
        {
            var personaIdParameter = personaId.HasValue ?
                new ObjectParameter("PersonaId", personaId) :
                new ObjectParameter("PersonaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RptAval_Result>("usp_RptAval", personaIdParameter);
        }
    
        public virtual ObjectResult<usp_RptCajaDiario_Result> usp_RptCajaDiario(Nullable<int> usuarioId, Nullable<int> oficinaId, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var oficinaIdParameter = oficinaId.HasValue ?
                new ObjectParameter("OficinaId", oficinaId) :
                new ObjectParameter("OficinaId", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RptCajaDiario_Result>("usp_RptCajaDiario", usuarioIdParameter, oficinaIdParameter, fechaInicioParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<usp_RptClientesInactivos_Result> usp_RptClientesInactivos(Nullable<int> usuarioId, Nullable<int> oficinaId, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var oficinaIdParameter = oficinaId.HasValue ?
                new ObjectParameter("OficinaId", oficinaId) :
                new ObjectParameter("OficinaId", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RptClientesInactivos_Result>("usp_RptClientesInactivos", usuarioIdParameter, oficinaIdParameter, fechaInicioParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<usp_RptCredito_Result> usp_RptCredito(Nullable<int> oficinaId, Nullable<int> gestorId, string estado, Nullable<System.DateTime> fechaDesIni, Nullable<System.DateTime> fechaDesFin)
        {
            var oficinaIdParameter = oficinaId.HasValue ?
                new ObjectParameter("OficinaId", oficinaId) :
                new ObjectParameter("OficinaId", typeof(int));
    
            var gestorIdParameter = gestorId.HasValue ?
                new ObjectParameter("GestorId", gestorId) :
                new ObjectParameter("GestorId", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            var fechaDesIniParameter = fechaDesIni.HasValue ?
                new ObjectParameter("FechaDesIni", fechaDesIni) :
                new ObjectParameter("FechaDesIni", typeof(System.DateTime));
    
            var fechaDesFinParameter = fechaDesFin.HasValue ?
                new ObjectParameter("FechaDesFin", fechaDesFin) :
                new ObjectParameter("FechaDesFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RptCredito_Result>("usp_RptCredito", oficinaIdParameter, gestorIdParameter, estadoParameter, fechaDesIniParameter, fechaDesFinParameter);
        }
    
        public virtual ObjectResult<usp_RptCreditoAprobacion_Result> usp_RptCreditoAprobacion(Nullable<System.DateTime> fechaAprobacion, Nullable<int> usuarioId, Nullable<int> oficinaId)
        {
            var fechaAprobacionParameter = fechaAprobacion.HasValue ?
                new ObjectParameter("FechaAprobacion", fechaAprobacion) :
                new ObjectParameter("FechaAprobacion", typeof(System.DateTime));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var oficinaIdParameter = oficinaId.HasValue ?
                new ObjectParameter("OficinaId", oficinaId) :
                new ObjectParameter("OficinaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RptCreditoAprobacion_Result>("usp_RptCreditoAprobacion", fechaAprobacionParameter, usuarioIdParameter, oficinaIdParameter);
        }
    
        public virtual ObjectResult<usp_RptCreditoMorosidad_Result> usp_RptCreditoMorosidad(Nullable<int> oficinaId, Nullable<System.DateTime> hastaFecha, Nullable<int> diasAtrazoIni, Nullable<int> diasAtrazoFin)
        {
            var oficinaIdParameter = oficinaId.HasValue ?
                new ObjectParameter("OficinaId", oficinaId) :
                new ObjectParameter("OficinaId", typeof(int));
    
            var hastaFechaParameter = hastaFecha.HasValue ?
                new ObjectParameter("HastaFecha", hastaFecha) :
                new ObjectParameter("HastaFecha", typeof(System.DateTime));
    
            var diasAtrazoIniParameter = diasAtrazoIni.HasValue ?
                new ObjectParameter("DiasAtrazoIni", diasAtrazoIni) :
                new ObjectParameter("DiasAtrazoIni", typeof(int));
    
            var diasAtrazoFinParameter = diasAtrazoFin.HasValue ?
                new ObjectParameter("DiasAtrazoFin", diasAtrazoFin) :
                new ObjectParameter("DiasAtrazoFin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RptCreditoMorosidad_Result>("usp_RptCreditoMorosidad", oficinaIdParameter, hastaFechaParameter, diasAtrazoIniParameter, diasAtrazoFinParameter);
        }
    
        public virtual ObjectResult<usp_RptCreditoRentabilidad_Result> usp_RptCreditoRentabilidad(Nullable<int> oficnaId, Nullable<System.DateTime> fechaIni, Nullable<System.DateTime> fechaFin, string estadoCredito)
        {
            var oficnaIdParameter = oficnaId.HasValue ?
                new ObjectParameter("OficnaId", oficnaId) :
                new ObjectParameter("OficnaId", typeof(int));
    
            var fechaIniParameter = fechaIni.HasValue ?
                new ObjectParameter("FechaIni", fechaIni) :
                new ObjectParameter("FechaIni", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var estadoCreditoParameter = estadoCredito != null ?
                new ObjectParameter("EstadoCredito", estadoCredito) :
                new ObjectParameter("EstadoCredito", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RptCreditoRentabilidad_Result>("usp_RptCreditoRentabilidad", oficnaIdParameter, fechaIniParameter, fechaFinParameter, estadoCreditoParameter);
        }
    
        public virtual ObjectResult<usp_RptCreditosActivos_Result> usp_RptCreditosActivos(Nullable<System.DateTime> fechaIni, Nullable<System.DateTime> fechaFin, Nullable<int> usuarioId, Nullable<int> oficinaId)
        {
            var fechaIniParameter = fechaIni.HasValue ?
                new ObjectParameter("FechaIni", fechaIni) :
                new ObjectParameter("FechaIni", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var oficinaIdParameter = oficinaId.HasValue ?
                new ObjectParameter("OficinaId", oficinaId) :
                new ObjectParameter("OficinaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RptCreditosActivos_Result>("usp_RptCreditosActivos", fechaIniParameter, fechaFinParameter, usuarioIdParameter, oficinaIdParameter);
        }
    
        public virtual ObjectResult<usp_RptCreditosCierres_Result> usp_RptCreditosCierres(Nullable<System.DateTime> fechaIni, Nullable<System.DateTime> fechaFin, Nullable<int> usuarioId, Nullable<int> oficinaId)
        {
            var fechaIniParameter = fechaIni.HasValue ?
                new ObjectParameter("FechaIni", fechaIni) :
                new ObjectParameter("FechaIni", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var oficinaIdParameter = oficinaId.HasValue ?
                new ObjectParameter("OficinaId", oficinaId) :
                new ObjectParameter("OficinaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RptCreditosCierres_Result>("usp_RptCreditosCierres", fechaIniParameter, fechaFinParameter, usuarioIdParameter, oficinaIdParameter);
        }
    
        public virtual ObjectResult<usp_RptCreditosMorososPagados_Result> usp_RptCreditosMorososPagados(Nullable<int> usuarioId, Nullable<int> oficinaId, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var oficinaIdParameter = oficinaId.HasValue ?
                new ObjectParameter("OficinaId", oficinaId) :
                new ObjectParameter("OficinaId", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RptCreditosMorososPagados_Result>("usp_RptCreditosMorososPagados", usuarioIdParameter, oficinaIdParameter, fechaInicioParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<usp_RptCreditoVencido_Result> usp_RptCreditoVencido(string vencidoMenor60, string vencidoMayor60, string vencidoIrrecuperable)
        {
            var vencidoMenor60Parameter = vencidoMenor60 != null ?
                new ObjectParameter("VencidoMenor60", vencidoMenor60) :
                new ObjectParameter("VencidoMenor60", typeof(string));
    
            var vencidoMayor60Parameter = vencidoMayor60 != null ?
                new ObjectParameter("VencidoMayor60", vencidoMayor60) :
                new ObjectParameter("VencidoMayor60", typeof(string));
    
            var vencidoIrrecuperableParameter = vencidoIrrecuperable != null ?
                new ObjectParameter("VencidoIrrecuperable", vencidoIrrecuperable) :
                new ObjectParameter("VencidoIrrecuperable", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RptCreditoVencido_Result>("usp_RptCreditoVencido", vencidoMenor60Parameter, vencidoMayor60Parameter, vencidoIrrecuperableParameter);
        }
    
        public virtual ObjectResult<usp_RptMovimientoCajaAnulado_Result> usp_RptMovimientoCajaAnulado(Nullable<System.DateTime> fechaIni, Nullable<System.DateTime> fechaFin)
        {
            var fechaIniParameter = fechaIni.HasValue ?
                new ObjectParameter("FechaIni", fechaIni) :
                new ObjectParameter("FechaIni", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RptMovimientoCajaAnulado_Result>("usp_RptMovimientoCajaAnulado", fechaIniParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<usp_RptMovimientoCredito_Result> usp_RptMovimientoCredito(Nullable<int> creditoId)
        {
            var creditoIdParameter = creditoId.HasValue ?
                new ObjectParameter("CreditoId", creditoId) :
                new ObjectParameter("CreditoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RptMovimientoCredito_Result>("usp_RptMovimientoCredito", creditoIdParameter);
        }
    
        public virtual ObjectResult<usp_RptSaldoCarteraCajaDiario_Result> usp_RptSaldoCarteraCajaDiario(Nullable<int> usuarioId, Nullable<int> oficinaId, Nullable<int> anioIni, Nullable<int> mesIni, Nullable<int> anioFin, Nullable<int> mesFin)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var oficinaIdParameter = oficinaId.HasValue ?
                new ObjectParameter("OficinaId", oficinaId) :
                new ObjectParameter("OficinaId", typeof(int));
    
            var anioIniParameter = anioIni.HasValue ?
                new ObjectParameter("AnioIni", anioIni) :
                new ObjectParameter("AnioIni", typeof(int));
    
            var mesIniParameter = mesIni.HasValue ?
                new ObjectParameter("MesIni", mesIni) :
                new ObjectParameter("MesIni", typeof(int));
    
            var anioFinParameter = anioFin.HasValue ?
                new ObjectParameter("AnioFin", anioFin) :
                new ObjectParameter("AnioFin", typeof(int));
    
            var mesFinParameter = mesFin.HasValue ?
                new ObjectParameter("MesFin", mesFin) :
                new ObjectParameter("MesFin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RptSaldoCarteraCajaDiario_Result>("usp_RptSaldoCarteraCajaDiario", usuarioIdParameter, oficinaIdParameter, anioIniParameter, mesIniParameter, anioFinParameter, mesFinParameter);
        }
    
        public virtual ObjectResult<usp_RptSaldosCaja_Result> usp_RptSaldosCaja(Nullable<int> cajaDiarioId, Nullable<bool> indCajaChica)
        {
            var cajaDiarioIdParameter = cajaDiarioId.HasValue ?
                new ObjectParameter("CajaDiarioId", cajaDiarioId) :
                new ObjectParameter("CajaDiarioId", typeof(int));
    
            var indCajaChicaParameter = indCajaChica.HasValue ?
                new ObjectParameter("IndCajaChica", indCajaChica) :
                new ObjectParameter("IndCajaChica", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RptSaldosCaja_Result>("usp_RptSaldosCaja", cajaDiarioIdParameter, indCajaChicaParameter);
        }
    
        public virtual ObjectResult<string> usp_RptSaldosCajaResumenIngreso(Nullable<int> cajaDiarioId, Nullable<int> oficinaId)
        {
            var cajaDiarioIdParameter = cajaDiarioId.HasValue ?
                new ObjectParameter("CajaDiarioId", cajaDiarioId) :
                new ObjectParameter("CajaDiarioId", typeof(int));
    
            var oficinaIdParameter = oficinaId.HasValue ?
                new ObjectParameter("OficinaId", oficinaId) :
                new ObjectParameter("OficinaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_RptSaldosCajaResumenIngreso", cajaDiarioIdParameter, oficinaIdParameter);
        }
    
        public virtual ObjectResult<usp_SimuladorCredito_Result> usp_SimuladorCredito(Nullable<decimal> monto, string formaPago, Nullable<int> nroCuotas, Nullable<decimal> interesMensual, Nullable<System.DateTime> fechaPrimerPago, Nullable<decimal> gastosAdm)
        {
            var montoParameter = monto.HasValue ?
                new ObjectParameter("Monto", monto) :
                new ObjectParameter("Monto", typeof(decimal));
    
            var formaPagoParameter = formaPago != null ?
                new ObjectParameter("FormaPago", formaPago) :
                new ObjectParameter("FormaPago", typeof(string));
    
            var nroCuotasParameter = nroCuotas.HasValue ?
                new ObjectParameter("NroCuotas", nroCuotas) :
                new ObjectParameter("NroCuotas", typeof(int));
    
            var interesMensualParameter = interesMensual.HasValue ?
                new ObjectParameter("InteresMensual", interesMensual) :
                new ObjectParameter("InteresMensual", typeof(decimal));
    
            var fechaPrimerPagoParameter = fechaPrimerPago.HasValue ?
                new ObjectParameter("FechaPrimerPago", fechaPrimerPago) :
                new ObjectParameter("FechaPrimerPago", typeof(System.DateTime));
    
            var gastosAdmParameter = gastosAdm.HasValue ?
                new ObjectParameter("GastosAdm", gastosAdm) :
                new ObjectParameter("GastosAdm", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SimuladorCredito_Result>("usp_SimuladorCredito", montoParameter, formaPagoParameter, nroCuotasParameter, interesMensualParameter, fechaPrimerPagoParameter, gastosAdmParameter);
        }
    
        public virtual int usp_SolicitudCredito_Del(Nullable<int> creditoId)
        {
            var creditoIdParameter = creditoId.HasValue ?
                new ObjectParameter("CreditoId", creditoId) :
                new ObjectParameter("CreditoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_SolicitudCredito_Del", creditoIdParameter);
        }
    
        public virtual int usp_TransferirBoveda(Nullable<int> bovedaInicioId, Nullable<int> bovedaDestinoId, string glosa, Nullable<decimal> monto, Nullable<int> usuarioRegId, Nullable<int> flagAceptar, Nullable<int> bovedaMovTempId)
        {
            var bovedaInicioIdParameter = bovedaInicioId.HasValue ?
                new ObjectParameter("BovedaInicioId", bovedaInicioId) :
                new ObjectParameter("BovedaInicioId", typeof(int));
    
            var bovedaDestinoIdParameter = bovedaDestinoId.HasValue ?
                new ObjectParameter("BovedaDestinoId", bovedaDestinoId) :
                new ObjectParameter("BovedaDestinoId", typeof(int));
    
            var glosaParameter = glosa != null ?
                new ObjectParameter("Glosa", glosa) :
                new ObjectParameter("Glosa", typeof(string));
    
            var montoParameter = monto.HasValue ?
                new ObjectParameter("Monto", monto) :
                new ObjectParameter("Monto", typeof(decimal));
    
            var usuarioRegIdParameter = usuarioRegId.HasValue ?
                new ObjectParameter("UsuarioRegId", usuarioRegId) :
                new ObjectParameter("UsuarioRegId", typeof(int));
    
            var flagAceptarParameter = flagAceptar.HasValue ?
                new ObjectParameter("flagAceptar", flagAceptar) :
                new ObjectParameter("flagAceptar", typeof(int));
    
            var bovedaMovTempIdParameter = bovedaMovTempId.HasValue ?
                new ObjectParameter("BovedaMovTempId", bovedaMovTempId) :
                new ObjectParameter("BovedaMovTempId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_TransferirBoveda", bovedaInicioIdParameter, bovedaDestinoIdParameter, glosaParameter, montoParameter, usuarioRegIdParameter, flagAceptarParameter, bovedaMovTempIdParameter);
        }
    
        public virtual ObjectResult<usp_UsuariosNoAsignadosCaja_Result> usp_UsuariosNoAsignadosCaja(Nullable<int> oficinaId)
        {
            var oficinaIdParameter = oficinaId.HasValue ?
                new ObjectParameter("OficinaId", oficinaId) :
                new ObjectParameter("OficinaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_UsuariosNoAsignadosCaja_Result>("usp_UsuariosNoAsignadosCaja", oficinaIdParameter);
        }
    
        public virtual int usp_AgregarPuntos(Nullable<decimal> codCliente, Nullable<int> ordenVentaId)
        {
            var codClienteParameter = codCliente.HasValue ?
                new ObjectParameter("CodCliente", codCliente) :
                new ObjectParameter("CodCliente", typeof(decimal));
    
            var ordenVentaIdParameter = ordenVentaId.HasValue ?
                new ObjectParameter("OrdenVentaId", ordenVentaId) :
                new ObjectParameter("OrdenVentaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_AgregarPuntos", codClienteParameter, ordenVentaIdParameter);
        }
    
        public virtual ObjectResult<string> usp_CanjearPuntos(Nullable<decimal> codCliente, string numeroSerie)
        {
            var codClienteParameter = codCliente.HasValue ?
                new ObjectParameter("CodCliente", codCliente) :
                new ObjectParameter("CodCliente", typeof(decimal));
    
            var numeroSerieParameter = numeroSerie != null ?
                new ObjectParameter("NumeroSerie", numeroSerie) :
                new ObjectParameter("NumeroSerie", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_CanjearPuntos", codClienteParameter, numeroSerieParameter);
        }
    
        public virtual ObjectResult<usp_MenuLst_Result> usp_MenuLst(Nullable<int> oficinaId, Nullable<int> usuarioId)
        {
            var oficinaIdParameter = oficinaId.HasValue ?
                new ObjectParameter("OficinaId", oficinaId) :
                new ObjectParameter("OficinaId", typeof(int));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_MenuLst_Result>("usp_MenuLst", oficinaIdParameter, usuarioIdParameter);
        }
    
        public virtual ObjectResult<usp_CodigoBarras_Lst_Result> usp_CodigoBarras_Lst(Nullable<int> pMovimientoId)
        {
            var pMovimientoIdParameter = pMovimientoId.HasValue ?
                new ObjectParameter("pMovimientoId", pMovimientoId) :
                new ObjectParameter("pMovimientoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CodigoBarras_Lst_Result>("usp_CodigoBarras_Lst", pMovimientoIdParameter);
        }
    
        public virtual int usp_OrdenVenta_Del(Nullable<int> ordenVentaId, Nullable<int> ordenVentaDetId)
        {
            var ordenVentaIdParameter = ordenVentaId.HasValue ?
                new ObjectParameter("OrdenVentaId", ordenVentaId) :
                new ObjectParameter("OrdenVentaId", typeof(int));
    
            var ordenVentaDetIdParameter = ordenVentaDetId.HasValue ?
                new ObjectParameter("OrdenVentaDetId", ordenVentaDetId) :
                new ObjectParameter("OrdenVentaDetId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_OrdenVenta_Del", ordenVentaIdParameter, ordenVentaDetIdParameter);
        }
    
        public virtual ObjectResult<string> usp_OrdenVentaDet_Ins(Nullable<int> ordenVentaId, string numeroSerie, Nullable<int> usuarioId)
        {
            var ordenVentaIdParameter = ordenVentaId.HasValue ?
                new ObjectParameter("OrdenVentaId", ordenVentaId) :
                new ObjectParameter("OrdenVentaId", typeof(int));
    
            var numeroSerieParameter = numeroSerie != null ?
                new ObjectParameter("NumeroSerie", numeroSerie) :
                new ObjectParameter("NumeroSerie", typeof(string));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_OrdenVentaDet_Ins", ordenVentaIdParameter, numeroSerieParameter, usuarioIdParameter);
        }
    
        public virtual int usp_OrdenVentaDet_update(Nullable<int> ordenVentaDetId, Nullable<decimal> descuento)
        {
            var ordenVentaDetIdParameter = ordenVentaDetId.HasValue ?
                new ObjectParameter("OrdenVentaDetId", ordenVentaDetId) :
                new ObjectParameter("OrdenVentaDetId", typeof(int));
    
            var descuentoParameter = descuento.HasValue ?
                new ObjectParameter("Descuento", descuento) :
                new ObjectParameter("Descuento", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_OrdenVentaDet_update", ordenVentaDetIdParameter, descuentoParameter);
        }
    
        public virtual ObjectResult<usp_RptRentabilidadVenta_Result> usp_RptRentabilidadVenta(Nullable<System.DateTime> fechaIni, Nullable<System.DateTime> fechaFin, Nullable<bool> indContado, Nullable<bool> indCredito, Nullable<int> oficinaId)
        {
            var fechaIniParameter = fechaIni.HasValue ?
                new ObjectParameter("FechaIni", fechaIni) :
                new ObjectParameter("FechaIni", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var indContadoParameter = indContado.HasValue ?
                new ObjectParameter("IndContado", indContado) :
                new ObjectParameter("IndContado", typeof(bool));
    
            var indCreditoParameter = indCredito.HasValue ?
                new ObjectParameter("IndCredito", indCredito) :
                new ObjectParameter("IndCredito", typeof(bool));
    
            var oficinaIdParameter = oficinaId.HasValue ?
                new ObjectParameter("OficinaId", oficinaId) :
                new ObjectParameter("OficinaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RptRentabilidadVenta_Result>("usp_RptRentabilidadVenta", fechaIniParameter, fechaFinParameter, indContadoParameter, indCreditoParameter, oficinaIdParameter);
        }
    
        public virtual ObjectResult<uspCreditoVencido_Result> uspCreditoVencido(Nullable<int> creditoId)
        {
            var creditoIdParameter = creditoId.HasValue ?
                new ObjectParameter("CreditoId", creditoId) :
                new ObjectParameter("CreditoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspCreditoVencido_Result>("uspCreditoVencido", creditoIdParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> usp_ObtenerSaldoCuentaCajadiario(Nullable<int> cajaDiarioId, Nullable<int> tipoPagoId)
        {
            var cajaDiarioIdParameter = cajaDiarioId.HasValue ?
                new ObjectParameter("CajaDiarioId", cajaDiarioId) :
                new ObjectParameter("CajaDiarioId", typeof(int));
    
            var tipoPagoIdParameter = tipoPagoId.HasValue ?
                new ObjectParameter("TipoPagoId", tipoPagoId) :
                new ObjectParameter("TipoPagoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("usp_ObtenerSaldoCuentaCajadiario", cajaDiarioIdParameter, tipoPagoIdParameter);
        }
    
        public virtual int usp_CerrarCajasDiarios(Nullable<int> usuarioCierreId, Nullable<int> oficinaId, Nullable<decimal> sobrante)
        {
            var usuarioCierreIdParameter = usuarioCierreId.HasValue ?
                new ObjectParameter("UsuarioCierreId", usuarioCierreId) :
                new ObjectParameter("UsuarioCierreId", typeof(int));
    
            var oficinaIdParameter = oficinaId.HasValue ?
                new ObjectParameter("OficinaId", oficinaId) :
                new ObjectParameter("OficinaId", typeof(int));
    
            var sobranteParameter = sobrante.HasValue ?
                new ObjectParameter("Sobrante", sobrante) :
                new ObjectParameter("Sobrante", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CerrarCajasDiarios", usuarioCierreIdParameter, oficinaIdParameter, sobranteParameter);
        }
    
        public virtual ObjectResult<string> usp_ResumenCuentaBoveda(Nullable<int> bovedaId)
        {
            var bovedaIdParameter = bovedaId.HasValue ?
                new ObjectParameter("BovedaId", bovedaId) :
                new ObjectParameter("BovedaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_ResumenCuentaBoveda", bovedaIdParameter);
        }
    
        public virtual int usp_CerrarBoveda(Nullable<int> oficinaId, Nullable<int> usuarioRegId)
        {
            var oficinaIdParameter = oficinaId.HasValue ?
                new ObjectParameter("OficinaId", oficinaId) :
                new ObjectParameter("OficinaId", typeof(int));
    
            var usuarioRegIdParameter = usuarioRegId.HasValue ?
                new ObjectParameter("UsuarioRegId", usuarioRegId) :
                new ObjectParameter("UsuarioRegId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CerrarBoveda", oficinaIdParameter, usuarioRegIdParameter);
        }
    
        public virtual ObjectResult<usp_RptMovimientoBoveda_Result> usp_RptMovimientoBoveda(Nullable<int> bovedaId)
        {
            var bovedaIdParameter = bovedaId.HasValue ?
                new ObjectParameter("BovedaId", bovedaId) :
                new ObjectParameter("BovedaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RptMovimientoBoveda_Result>("usp_RptMovimientoBoveda", bovedaIdParameter);
        }
    
        public virtual ObjectResult<string> usp_RptSaldosCajaResumenTipoCuenta(Nullable<int> oficinaId)
        {
            var oficinaIdParameter = oficinaId.HasValue ?
                new ObjectParameter("OficinaId", oficinaId) :
                new ObjectParameter("OficinaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_RptSaldosCajaResumenTipoCuenta", oficinaIdParameter);
        }
    
        public virtual ObjectResult<usp_RptCajasAsignadas_Result> usp_RptCajasAsignadas(Nullable<int> oficinaId)
        {
            var oficinaIdParameter = oficinaId.HasValue ?
                new ObjectParameter("OficinaId", oficinaId) :
                new ObjectParameter("OficinaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RptCajasAsignadas_Result>("usp_RptCajasAsignadas", oficinaIdParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> usp_ObtenerMontoPendientePlanPago(Nullable<int> oficinaId)
        {
            var oficinaIdParameter = oficinaId.HasValue ?
                new ObjectParameter("OficinaId", oficinaId) :
                new ObjectParameter("OficinaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("usp_ObtenerMontoPendientePlanPago", oficinaIdParameter);
        }
    
        public virtual ObjectResult<usp_RptClientesBloqueados_Result> usp_RptClientesBloqueados(Nullable<int> oficinaId, Nullable<int> usuarioId)
        {
            var oficinaIdParameter = oficinaId.HasValue ?
                new ObjectParameter("OficinaId", oficinaId) :
                new ObjectParameter("OficinaId", typeof(int));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RptClientesBloqueados_Result>("usp_RptClientesBloqueados", oficinaIdParameter, usuarioIdParameter);
        }
    
        public virtual ObjectResult<usp_RptClientesTopeCredito_Result> usp_RptClientesTopeCredito(Nullable<int> oficinaId, Nullable<int> usuarioId)
        {
            var oficinaIdParameter = oficinaId.HasValue ?
                new ObjectParameter("OficinaId", oficinaId) :
                new ObjectParameter("OficinaId", typeof(int));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RptClientesTopeCredito_Result>("usp_RptClientesTopeCredito", oficinaIdParameter, usuarioIdParameter);
        }
    
        public virtual ObjectResult<usp_RptCobroDiarioDetalle_Result> usp_RptCobroDiarioDetalle(Nullable<int> usuarioId, Nullable<int> oficinaId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var oficinaIdParameter = oficinaId.HasValue ?
                new ObjectParameter("OficinaId", oficinaId) :
                new ObjectParameter("OficinaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RptCobroDiarioDetalle_Result>("usp_RptCobroDiarioDetalle", usuarioIdParameter, oficinaIdParameter);
        }
    
        public virtual ObjectResult<usp_RptCobroDiario_Result> usp_RptCobroDiario(Nullable<int> usuarioId, Nullable<int> oficinaId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var oficinaIdParameter = oficinaId.HasValue ?
                new ObjectParameter("OficinaId", oficinaId) :
                new ObjectParameter("OficinaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RptCobroDiario_Result>("usp_RptCobroDiario", usuarioIdParameter, oficinaIdParameter);
        }
    }
}
