//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITB.VENDIX.BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class BovedaMovTemp
    {
        public int BovedaMovTempId { get; set; }
        public int BovedaInicioId { get; set; }
        public int BovedaDestinoId { get; set; }
        public string CodOperacion { get; set; }
        public string Glosa { get; set; }
        public decimal Importe { get; set; }
        public int UsuarioRegId { get; set; }
        public int MovimientoBovedaIniId { get; set; }
        public System.DateTime FechaReg { get; set; }
        public bool IndEntrada { get; set; }
        public bool Estado { get; set; }
    
        public virtual Boveda Boveda { get; set; }
        public virtual Boveda Boveda1 { get; set; }
    }
}
