//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITB.VENDIX.BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caja
    {
        public Caja()
        {
            this.CajaDiario = new HashSet<CajaDiario>();
        }
    
        public int CajaId { get; set; }
        public int OficinaId { get; set; }
        public string Denominacion { get; set; }
        public bool Estado { get; set; }
        public int UsuarioRegId { get; set; }
        public System.DateTime FechaReg { get; set; }
        public bool IndAbierto { get; set; }
        public Nullable<int> UsuarioModId { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
        public Nullable<int> CajeroId { get; set; }
    
        public virtual Oficina Oficina { get; set; }
        public virtual ICollection<CajaDiario> CajaDiario { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
