//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITB.VENDIX.BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentralRiesgo
    {
        public int Anio { get; set; }
        public int Mes { get; set; }
        public int CreditoId { get; set; }
        public int DiasAtrazo { get; set; }
        public int CuotasAtrazo { get; set; }
        public decimal DeudaAtrazo { get; set; }
    
        public virtual Credito Credito { get; set; }
    }
}
