//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITB.VENDIX.BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaxCobrar
    {
        public int CuentaxCobrarId { get; set; }
        public string Operacion { get; set; }
        public decimal Monto { get; set; }
        public string Estado { get; set; }
        public Nullable<int> MovimientoCajaId { get; set; }
        public Nullable<int> CreditoId { get; set; }
    
        public virtual Credito Credito { get; set; }
        public virtual MovimientoCaja MovimientoCaja { get; set; }
    }
}
