//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITB.VENDIX.BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaPrecio
    {
        public int ListaPrecioId { get; set; }
        public Nullable<int> ArticuloId { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public bool Estado { get; set; }
        public Nullable<int> Puntos { get; set; }
        public Nullable<int> PuntosCanje { get; set; }
    
        public virtual Articulo Articulo { get; set; }
    }
}
