//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITB.VENDIX.BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.RolMenu = new HashSet<RolMenu>();
        }
    
        public int MenuId { get; set; }
        public string Denominacion { get; set; }
        public string Modulo { get; set; }
        public string Url { get; set; }
        public string Icono { get; set; }
        public Nullable<bool> IndPadre { get; set; }
        public Nullable<decimal> Orden { get; set; }
        public Nullable<decimal> Referencia { get; set; }
    
        public virtual ICollection<RolMenu> RolMenu { get; set; }
    }
}
