//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITB.VENDIX.BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoDet
    {
        public MovimientoDet()
        {
            this.SerieArticulo = new HashSet<SerieArticulo>();
        }
    
        public int MovimientoDetId { get; set; }
        public int MovimientoId { get; set; }
        public int ArticuloId { get; set; }
        public int Cantidad { get; set; }
        public string Descripcion { get; set; }
        public decimal PrecioUnitario { get; set; }
        public decimal Descuento { get; set; }
        public decimal Importe { get; set; }
        public bool IndCorrelativo { get; set; }
        public Nullable<int> UnidadMedidaT10 { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Movimiento Movimiento { get; set; }
        public virtual ICollection<SerieArticulo> SerieArticulo { get; set; }
    }
}
