//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITB.VENDIX.BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoCaja
    {
        public MovimientoCaja()
        {
            this.CuentaxCobrar = new HashSet<CuentaxCobrar>();
            this.MovimientoCajaAnu = new HashSet<MovimientoCajaAnu>();
            this.PlanPago = new HashSet<PlanPago>();
        }
    
        public int MovimientoCajaId { get; set; }
        public int CajaDiarioId { get; set; }
        public string Operacion { get; set; }
        public decimal ImportePago { get; set; }
        public Nullable<int> PersonaId { get; set; }
        public int TipoPagoId { get; set; }
        public string Descripcion { get; set; }
        public bool IndEntrada { get; set; }
        public bool Estado { get; set; }
        public int UsuarioRegId { get; set; }
        public System.DateTime FechaReg { get; set; }
        public Nullable<int> OrdenVentaId { get; set; }
        public Nullable<int> CreditoId { get; set; }
    
        public virtual CajaDiario CajaDiario { get; set; }
        public virtual Credito Credito { get; set; }
        public virtual ICollection<CuentaxCobrar> CuentaxCobrar { get; set; }
        public virtual MovimientoCajaExtension MovimientoCajaExtension { get; set; }
        public virtual ICollection<MovimientoCajaAnu> MovimientoCajaAnu { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual OrdenVenta OrdenVenta { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual ICollection<PlanPago> PlanPago { get; set; }
    }
}
