//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITB.VENDIX.BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoRendidoCajaChica
    {
        public int Id { get; set; }
        public int MovimientoCajaChicaId { get; set; }
        public int TipoDocumentoId { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Serie { get; set; }
        public string Numero { get; set; }
        public string RUC { get; set; }
        public string RazonSocial { get; set; }
        public string DetalleGasto { get; set; }
        public decimal Importe { get; set; }
    
        public virtual MovimientoCajaChica MovimientoCajaChica { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
    }
}
