//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITB.VENDIX.BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oficina
    {
        public Oficina()
        {
            this.Almacen = new HashSet<Almacen>();
            this.Boveda = new HashSet<Boveda>();
            this.Caja = new HashSet<Caja>();
            this.Credito = new HashSet<Credito>();
            this.UsuarioOficina = new HashSet<UsuarioOficina>();
            this.UsuarioRol = new HashSet<UsuarioRol>();
            this.OrdenVenta = new HashSet<OrdenVenta>();
        }
    
        public int OficinaId { get; set; }
        public string Denominacion { get; set; }
        public string Descripcion { get; set; }
        public string Telefono { get; set; }
        public bool IndPrincipal { get; set; }
        public bool Estado { get; set; }
        public int UsuarioAsignadoId { get; set; }
    
        public virtual ICollection<Almacen> Almacen { get; set; }
        public virtual ICollection<Boveda> Boveda { get; set; }
        public virtual ICollection<Caja> Caja { get; set; }
        public virtual ICollection<Credito> Credito { get; set; }
        public virtual ICollection<UsuarioOficina> UsuarioOficina { get; set; }
        public virtual ICollection<UsuarioRol> UsuarioRol { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<OrdenVenta> OrdenVenta { get; set; }
    }
}
