//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITB.VENDIX.BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaDepurado
    {
        public int PersonaDepuradoId { get; set; }
        public int PersonaId { get; set; }
        public string Descripcion { get; set; }
        public bool Estado { get; set; }
        public int UsuarioRegId { get; set; }
        public System.DateTime FechaReg { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
