//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITB.VENDIX.BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanPago
    {
        public int PlanPagoId { get; set; }
        public int CreditoId { get; set; }
        public int Numero { get; set; }
        public decimal Capital { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public decimal Amortizacion { get; set; }
        public decimal Interes { get; set; }
        public decimal GastosAdm { get; set; }
        public decimal Cuota { get; set; }
        public string Estado { get; set; }
        public int DiasAtrazo { get; set; }
        public decimal ImporteMora { get; set; }
        public decimal Descuento { get; set; }
        public Nullable<decimal> PagoCuota { get; set; }
        public Nullable<System.DateTime> FechaPagoCuota { get; set; }
        public Nullable<int> MovimientoCajaId { get; set; }
        public Nullable<int> UsuarioModId { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
        public decimal PagoLibre { get; set; }
        public decimal Cargo { get; set; }
    
        public virtual Credito Credito { get; set; }
        public virtual MovimientoCaja MovimientoCaja { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
