//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITB.VENDIX.BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol
    {
        public Rol()
        {
            this.RolMenu = new HashSet<RolMenu>();
            this.UsuarioRol = new HashSet<UsuarioRol>();
        }
    
        public int RolId { get; set; }
        public string Denominacion { get; set; }
        public bool Estado { get; set; }
    
        public virtual ICollection<RolMenu> RolMenu { get; set; }
        public virtual ICollection<UsuarioRol> UsuarioRol { get; set; }
    }
}
