//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITB.VENDIX.BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoMovimiento
    {
        public TipoMovimiento()
        {
            this.Movimiento = new HashSet<Movimiento>();
        }
    
        public int TipoMovimientoId { get; set; }
        public string Denominacion { get; set; }
        public string Descripcion { get; set; }
        public bool IndEntrada { get; set; }
        public Nullable<bool> IndTransferencia { get; set; }
        public Nullable<bool> IndDevolucion { get; set; }
        public bool Estado { get; set; }
    
        public virtual ICollection<Movimiento> Movimiento { get; set; }
    }
}
