namespace Credito.Modern.Application.Reportes;

/// <summary>Clave de informe con mapeo visual legacy (RDLC → columnas PDF).</summary>
public enum CredixLegacyReportKey
{
    CobroDiario,
    MorosidadGestor,
    ClientesInactivos,
    ClientesBloqueados,
    ClientesTopeCredito,
    CreditoObservado,
    ClientesNuevosMes,
    CreditoCondonado,
    CreditoRentabilidad,
    CreditoAprobacion,
    CreditosActivos,
    CreditosCierres,
    CreditosMorososPagados,
    ReporteCredito,
    CajaDiario,
    CreditoVencido,
    MovimientoCajaAnulado,
    SaldoCarteraCajaDiario,
    ComprobantesCajaChica,
    CajasAsignadas,
    CobroDiarioDetalle,
    CobranzaPagos,
    MovimientoCredito,
    ListarSaldoCartera,
    AvalPersona,
    SaldosCaja,
    MovimientoBoveda,
    CentralRiesgoGenerar,
    PagosNoVerificados,
    ReporteStock,
    StockAnulados,
    ListaPrecio,
    Kardex,
    RentabilidadVenta,
    CreditoMorosidad,
}
