namespace Credito.Modern.Application.Clientes;

/// <summary>Paridad <c>ClienteController.ObtenerClientePersona</c> / formulario Mantener.</summary>
public sealed record ClienteDetalleDto(
    int PersonaId,
    int ClienteId,
    string TipoPersona,
    string Nombre,
    string? ApePaterno,
    string? ApeMaterno,
    string NumeroDocumento,
    string TipoDocumento,
    string Sexo,
    string? Email,
    string? Celular1,
    string? Direccion,
    string? DireccionRef,
    int? DistritoId,
    string? DistritoLabel,
    DateTime? FechaNacimiento,
    int? ActividadEconId,
    string Calificacion,
    string? Nota,
    bool ClienteEstado,
    bool PersonaEstado,
    bool Bloqueado,
    decimal? TopeCredito,
    int? EstadoCivilId,
    int? TipoViviendaId,
    int? ConyuguePersonaId,
    string? ConyugueLabel,
    int? ClasificacionRiesgoSbsId,
    string? ClasificacionRiesgoSbsObs,
    string? DireccionNegocio,
    string? DireccionNegocioRef,
    decimal? Latitud,
    decimal? Longitud,
    string? DepuradoDescripcion);
